# Generated by Django 2.1.7 on 2019-03-12 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0013_auto_20190312_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.Continent'),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.Country'),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='country2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showcase_country2_set', to='demo.Country', verbose_name='Django Select 2'),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='raw_id_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showcase_raw_set', to='demo.Country'),
        ),
    ]
